---
title: "leafletX"
author: "wenlarry"
date: "2/14/2017"
output: html_document
---
```{r, echo=FALSE}
library(leaflet)
my_map<- leaflet() %>%
 addTiles
my_map
```
# Add Legends

```{r,echo=FALSE} 
df<-data.frame(lat=runif(20,min=39.25,max=39.35),   
               lng=runif(20,min=-76.65,max=-76.55),   
               col=sample(c("purple","orange","green"),20,
                          replace=TRUE),  
               stringsAsFactors=FALSE)    
 
df%>%
 leaflet()%>%
 addTiles()%>%
 addCircleMarkers(color=df$col)%>%  
 addLegend(labels=LETTERS[1:3],colors=c("purple","orange","green")) 

```
# Mapping Clusters

```{r echo=FALSE}
df<-data.frame(lat=runif(500,min=39.25,max=39.35),    
               lng=runif(500,min=-76.65,max=-76.55) )
               
df%>%
 leaflet() %>%
 addTiles()%>%
 addMarkers(clusterOptions=markerClusterOptions())

```

Draw Circles

```{r, echo=FALSE} 
cities<-data.frame(name=c("Baltimore", "Annapolis"),
                    pop=c(619493, 38880),
                    lat=c(39.2920592, 38.9784),
                    lng=c(-76.6077852, -76.4922))
         
cities%>% 
 leaflet()%>% 
 addTiles()%>% 
 addCircles(weight=1,radius=sqrt(cities$pop)*30)

```

 


 
 